anifriends/Anifriends-Backend

anifriends/.gitignore, anifriends/build.gradle
QueryDSL 세팅
- `build.gradle` 에 queryDSL 설정을 위한 코드 추가
- `.gitignore`에 `/src/main/generated` 추가함으로써 Q 클래스 원격 저장소에 올라가지 못하게 함
- close #9
=> chore: QueryDSL 세팅한다.

.github/workflows/CD.yml, appspec.yml, scripts/deploy.sh
- Github Action + S3 + CodeDeploy를 이용한 애플리케이션 배포 설정을 추가하였습니다.
- CodeDeploy를 위한 설정 파일(appspec.yml, deploy.sh) 추가
- 배포 설정을 위한 워크플로우(CD.yml) 추가
- close #20
=> chore: CD를 설정한다.

src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java, src/main/java/com/clova/anifriends/domain/volunteer/VolunteerImage.java, src/main/java/com/clova/anifriends/domain/volunteer/controller/VolunteerController.java, src/main/java/com/clova/anifriends/domain/volunteer/dto/request/RegisterVolunteerRequest.java, src/main/java/com/clova/anifriends/domain/volunteer/exception/NotFoundVolunteerGenderException.java, src/main/java/com/clova/anifriends/domain/volunteer/exception/VolunteerBadRequestException.java, src/main/java/com/clova/anifriends/domain/volunteer/repository/VolunteerImageRepository.java, src/main/java/com/clova/anifriends/domain/volunteer/service/VolunteerService.java, src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerEmail.java, src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerGender.java, src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerName.java, src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerPassword.java, src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerPhoneNumber.java, src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerTemperature.java, src/test/java/com/clova/anifriends/base/BaseControllerTest.java, src/test/java/com/clova/anifriends/domain/volunteer/VolunteerTest.java, src/test/java/com/clova/anifriends/domain/volunteer/controller/VolunteerControllerTest.java, src/test/java/com/clova/anifriends/domain/volunteer/service/VolunteerServiceTest.java, src/test/java/com/clova/anifriends/domain/volunteer/support/VolunteerDtoFixture.java, src/test/java/com/clova/anifriends/domain/volunteer/support/VolunteerFixture.java, src/test/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerEmailTest.java, src/test/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerGenderTest.java, src/test/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerNameTest.java, src/test/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerPasswordTest.java, src/test/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerPhoneNumberTest.java, src/test/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerTemperatureTest.java
봉사자 회원가입 API
- 봉사자 회원가입 controller, service, requestDTO 작성
- 봉사자 회원가입 requestDTO 작성
- 봉사자 관련 도메인 검증 로직 작성
- 관련 테스트 작성
- close #34
=> feat: 봉사자 회원가입 로직을 구현한다. 

src/main/java/com/clova/anifriends/domain/shelter/controller/ShelterController.java, src/main/java/com/clova/anifriends/domain/shelter/dto/FindShelterMyPageResponse.java, src/main/java/com/clova/anifriends/domain/shelter/service/ShelterService.java, src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterName.java, src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterPassword.java, src/test/java/com/clova/anifriends/base/BaseControllerTest.java, src/test/java/com/clova/anifriends/domain/auth/resolver/LoginUserArgumentResolverTest.java, src/test/java/com/clova/anifriends/domain/auth/support/AuthFixture.java, src/test/java/com/clova/anifriends/domain/shelter/controller/ShelterControllerTest.java, src/test/java/com/clova/anifriends/domain/shelter/service/ShelterServiceTest.java
- 보호소 마이페이지 서비스, 컨트롤러 로직 구현
- 보호소 마이페이지 서비스, 컨트롤러 테스트 코드 작성
- BaseControllerTest에 shelterAccessToken을 추가
- 보호소 controller에 shelterAccessToken 적용
- 보호소 마이페이지 서비스, 컨트롤러 로직 구현
- close #50
=> feat: 마이페이지 조회 로직을 구현한다. (보호소)

src/test/java/com/clova/anifriends/domain/volunteer/controller/VolunteerControllerTest.java
봉사자 마이페이지에서 imageUrl은 optional이다.
마이페이지 조회 controller test에서 imageUrl optional로 한다.
- close #60
=> fix: 봉사자 마이페이지에서 imageUrl은 optional이다.

src/main/java/com/clova/anifriends/domain/common/dto/PageInfo.java, src/main/java/com/clova/anifriends/domain/recruitment/Recruitment.java, src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java, src/main/java/com/clova/anifriends/domain/recruitment/dto/request/FindRecruitmentsByShelterRequest.java, src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentsByShelterResponse.java, src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepository.java, src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryCustom.java, src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryImpl.java, src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java, src/main/java/com/clova/anifriends/domain/review/repository/ReviewRepository.java, src/main/java/com/clova/anifriends/global/config/QueryDslConfig.java, src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java, src/test/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryImplTest.java, src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java, src/test/java/com/clova/anifriends/domain/recruitment/support/fixture/RecruitmentDtoFixture.java
- 보호소의 봉사 모집글 조회 및 검색 api
- 보호소의 봉사 모집글 조회, 검색 api 구현
- QueryDSL Config 작성
- 관련 테스트 코드 작성
- close #65
=> feat: 보호소에서 모집글을 조회 및 검색한다.

src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java, src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepository.java, src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java, src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java, src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
보호소의 모집글 상세조회에서 보호소 Id 와 모집글 Id 로 조회하도록 변경했습니다.
- 보호소의 모집글 상세조회에서 보호소 Id 와 모집글 Id 로 조회하도록 변경
- close #58
=> fix: 보호소의 모집글 상세조회에서 보호소 Id 와 모집글 Id 로 조회하도록 변경

appspec.yml
- CodeDeploy가 배포한 파일들에 접근 불가능한 문제를 해결하기 위해 쉘스크립트에 permission 설정을 추가하였습니다.
- `deploy.sh` `permissions` 항목 추가
- close #103
=> fix: CodeDeploy permission denied를 해결한다.

src/main/java/com/clova/anifriends/domain/animal/AnimalAge.java, src/main/java/com/clova/anifriends/domain/animal/controller/AnimalController.java, src/main/java/com/clova/anifriends/domain/animal/dto/request/FindAnimalsByVolunteerRequest.java, src/main/java/com/clova/anifriends/domain/animal/dto/response/FindAnimalsByVolunteerResponse.java, src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryCustom.java, src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryImpl.java, src/main/java/com/clova/anifriends/domain/animal/service/AnimalService.java, src/test/java/com/clova/anifriends/domain/animal/controller/AnimalControllerTest.java, src/test/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryImplTest.java, src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceTest.java
봉사자 입장의 보호 동물 검색 조회 로직을 구현했습니다.
- 보호 동물 필터링 검색을 위한 동적 쿼리 구현
- 레포지토리 테스트코드 작성
- 보호 동물 검색 조회 서비스 구현
- 보호 동물 검색 조회 서비스 테스트코드 작성
- 보호 동물 검색 조회 컨트롤러 구현
- 보호 동물 검색 조회 컨트롤러 테스트코드 작성
- close #67
=> feat: 보호 동물 검색 조회 로직을 구현한다.(봉사자)

src/main/java/com/clova/anifriends/domain/applicant/dto/FindApplyingVolunteersResponse.java, src/test/java/com/clova/anifriends/domain/applicant/controller/ApplicantControllerTest.java, src/test/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepositoryTest.java, src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantServiceTest.java
- API 명세에 맞게 FindApplyingVolunteerResponse에 shelterId 추가 및 응답 필드명 수정
- 봉사자가 신청한 봉사 리스트 조회(봉사자)를 명세에 맞게 수정
- close #132
=> refactor: 봉사자가 신청한 봉사 리스트 조회(봉사자)를 명세에 맞게 수정한다.

src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentsByShelterIdResponse.java, src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryImpl.java, src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java, src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java, src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java, src/test/java/com/clova/anifriends/domain/recruitment/support/fixture/RecruitmentDtoFixture.java
보호소에 달린 봉사 모집글 리스트 조회(공통)을 명세에 맞게 수정한다. 
- responseDTO 변경
- 레포지토리 함수에서 직접 count 계산하여 Page 객체에 넣어주기
- 테스트 코드 변경
- close #126
=> factor: 보호소에 달린 봉사 모집글 리스트 조회(공통)을 명세에 맞게 수정한다. 

src/main/java/com/clova/anifriends/domain/volunteer/dto/response/FindVolunteerMyPageResponse.java, src/test/java/com/clova/anifriends/domain/volunteer/controller/VolunteerControllerTest.java, src/test/java/com/clova/anifriends/domain/volunteer/service/VolunteerServiceTest.java, src/test/java/com/clova/anifriends/domain/volunteer/support/VolunteerDtoFixture.java
마이페이지 조회(봉사자)를 명세에 맞게 수정한다. 
- responseDTO 수정
- 테스트 코드 수정
- close #131
=> refactor: 마이페이지 조회(봉사자)를 명세에 맞게 수정한다. 

src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentsByShelterResponse.java, src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryImpl.java, src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java, src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java, src/test/java/com/clova/anifriends/domain/recruitment/support/fixture/RecruitmentDtoFixture.java
모집글 조회 & 검색(보호소)를 명세에 맞게 수정한다. 
- responseDTO 변경
- 테스트 코드 수정
- 쿼리 함수에서 Page 객체에 직접 count 계산하여 넣기
- close #133
=> refactor: 모집글 조회 & 검색(보호소)를 명세에 맞게 수정한다. 

src/main/java/com/clova/anifriends/domain/applicant/Applicant.java, src/main/java/com/clova/anifriends/domain/applicant/controller/ApplicantController.java, src/main/java/com/clova/anifriends/domain/applicant/dto/FindApplicantsResponse.java, src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java, src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantService.java, src/main/java/com/clova/anifriends/domain/applicant/wrapper/ApplicantStatus.java, src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java, src/test/java/com/clova/anifriends/domain/applicant/controller/ApplicantControllerTest.java, src/test/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepositoryTest.java, src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantServiceTest.java
봉사 신청 현황 조회 로직을 구현했습니다.
- 봉사 신청자 조회 레포지토리 구현
- 봉사 신청자 조회 레포지토리 테스트코드 작성
- 봉사 신청자 조회 서비스 구현
- 봉사 신청자 조회 서비스 테스트코드 작성
- 봉사 신청자 조회 컨트롤러 구현
- 봉사 신청자 조회 컨트롤러 테스트코드 작성
- close #68
=> feat: 봉사 신청 현황 조회 로직을 구현한다.

src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java, src/main/java/com/clova/anifriends/domain/volunteer/service/VolunteerService.java, src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerPassword.java, src/test/java/com/clova/anifriends/domain/auth/service/AuthServiceTest.java, src/test/java/com/clova/anifriends/domain/volunteer/VolunteerTest.java, src/test/java/com/clova/anifriends/domain/volunteer/service/VolunteerServiceTest.java, src/test/java/com/clova/anifriends/domain/volunteer/support/VolunteerFixture.java, src/test/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerPasswordTest.java
- 봉사자 회원가입 로직에 패스워드 인코딩 추가
- VolunteerPassword에서 passwordEncoder를 받아 rawPassword에 대한 validation을 마친 후 인코딩한 패스워드를 저장한다.
- service 단에서 passwordEncoder를 넘겨준다.
- 봉사자 회원가입 로직에 패스워드 인코딩 추가
- 관련 테스트 코드 수정
- close #138
=> refactor: 회원가입(봉사자) 로직에 패스워드 인코딩을 추가한다.

src/main/java/com/clova/anifriends/domain/review/dto/response/FindShelterReviewsByShelterResponse.java, src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
- 프론트엔드의 요청에 따라 보호소가 후기 리스트를 조회시 응답 필드에 volunteerId를 추가하였습니다.
- 보호소가 받은 후기 리스트 조회(보호소) api 응답 필드 추가
- close #208
=> feat: 보호소가 받은 후기 리스트 조회(보호소) api 응답 필드를 추가한다.

src/main/java/com/clova/anifriends/domain/auth/authentication/JwtAuthentication.java, src/main/java/com/clova/anifriends/domain/auth/authentication/JwtAuthenticationProvider.java, src/main/java/com/clova/anifriends/domain/auth/dto/response/CustomClaims.java, src/main/java/com/clova/anifriends/global/security/jwt/JJwtProvider.java, src/main/java/com/clova/anifriends/global/web/argumentresolver/LoginUserArgumentResolver.java, src/test/java/com/clova/anifriends/domain/auth/authentication/JwtAuthenticationProviderTest.java, src/test/java/com/clova/anifriends/domain/auth/resolver/LoginUserArgumentResolverTest.java, src/test/java/com/clova/anifriends/domain/auth/resolver/LoginUserTestController.java
- 인증 객체의 principal인 JwtAuthentication에 사용자 역할 필드를 추가하였습니다.
- 사용자의 역할에 대한 정보가 필요한 경우 컨트롤러의 시그니처에 JwtAuthentication 타입의 파라미터를 추가해주시고 스프링 시큐리티가 제공하는 `@AuthenticationPrincipal`을 파라미터 앞에 명시해주시면 됩니다.
- JwtAuthentication에 사용자 역할 필드 추가
- close #224
=> feat: 인증 객체 principal에 역할 필드를 추가한다.

src/main/java/com/clova/anifriends/domain/notification/controller/ShelterNotificationController.java, src/main/java/com/clova/anifriends/domain/notification/dto/response/FindShelterHasNewNotificationResponse.java, src/main/java/com/clova/anifriends/domain/notification/repository/ShelterNotificationRepository.java, src/main/java/com/clova/anifriends/domain/notification/service/ShelterNotificationService.java, src/test/java/com/clova/anifriends/domain/notification/controller/ShelterNotificationControllerTest.java, src/test/java/com/clova/anifriends/domain/notification/repository/ShelterNotificationRepositoryTest.java, src/test/java/com/clova/anifriends/domain/notification/service/ShelterNotificationServiceTest.java
보호소 새로운 알림 여부 조회 API 구현
- 보호소 새로운 알림 존재 여부 조회를 위해 쿼리, 컨트롤러단 메서드, 서비스단 메서드 작성
- 테스트 코드 작성
- close #198
=> feat: 보호소 새로운 알림 여부 조회 API를 구현한다.

src/main/java/com/clova/anifriends/domain/chat/ChatMessage.java, src/main/java/com/clova/anifriends/domain/chat/controller/ChatMessageController.java, src/main/java/com/clova/anifriends/domain/chat/exception/ChatMessageBadRequestException.java, src/main/java/com/clova/anifriends/domain/chat/exception/ChatRoomNotFoundException.java, src/main/java/com/clova/anifriends/domain/chat/message/pub/NewChatMessagePub.java, src/main/java/com/clova/anifriends/domain/chat/message/sub/ChatMessageSub.java, src/main/java/com/clova/anifriends/domain/chat/service/ChatMessageService.java, src/test/java/com/clova/anifriends/base/BaseControllerTest.java, src/test/java/com/clova/anifriends/domain/chat/ChatMessageTest.java, src/test/java/com/clova/anifriends/domain/chat/controller/WebSocketStompTest.java, src/test/java/com/clova/anifriends/domain/chat/service/ChatMessageServiceTest.java, src/test/java/com/clova/anifriends/domain/chat/support/ChatMessageFixture.java
새로운 채팅방에서 메시지 발생 시 메시지를 publish 처리를 하였습니다.
- 새로운 채팅방 생성 시 클라이언트에서 `/pub/new/chat/rooms/{chatRoomId}/shelters/{shelterId}` 로 메시지 전송
- 서버에서는 메시지를 저장하고 `/sub/new/chat/rooms/shelters/{shelterId}` 로 메시지 발행 처리
- 서버와 클라이언트의 STOMP pub/sub 메시지를 검증하는 테스트코드 작성
1. 클라이언트에서 `/pub/new/chat/rooms/{chatRoomId}/shelters/{shelterId}` 로 메시지 PUB
2. 서버에서 `/sub/new/chat/rooms/shelters/{shelterId}` 로 메시지 PUB
(서버측에서 메시지를 PUB할때 목데이터를 사용하여 발신 메시지와 수신 메시지가 다릅니다.)
- close #225
=> feat: 새로운 채팅방에서 메시지 발생 시 메시지를 publish 한다.

src/main/java/com/clova/anifriends/domain/notification/controller/VolunteerNotificationController.java, src/main/java/com/clova/anifriends/domain/notification/dto/response/FindVolunteerHasNewNotificationResponse.java, src/main/java/com/clova/anifriends/domain/notification/dto/response/FindVolunteerNotificationsResponse.java, src/main/java/com/clova/anifriends/domain/notification/repository/VolunteerNotificationRepository.java, src/main/java/com/clova/anifriends/domain/notification/service/VolunteerNotificationService.java, src/test/java/com/clova/anifriends/domain/notification/controller/ShelterNotificationControllerTest.java, src/test/java/com/clova/anifriends/domain/notification/controller/VolunteerNotificationControllerTest.java, src/test/java/com/clova/anifriends/domain/notification/repository/VolunteerNotificationRepositoryTest.java, src/test/java/com/clova/anifriends/domain/notification/service/VolunteerNotificationServiceTest.java
봉사자 새로운 알림 여부 조회 API 구현
- 봉사자 새로운 알림 존재 여부 조회를 위해 쿼리, 컨트롤러단 메서드, 서비스단 메서드 작성
- 테스트 코드 작성
- close #231
=> feat: 봉사자 새로운 알림 여부 조회 API를 구현한다.

src/main/java/com/clova/anifriends/domain/notification/controller/ShelterNotificationController.java, src/main/java/com/clova/anifriends/domain/notification/repository/ShelterNotificationRepository.java, src/main/java/com/clova/anifriends/domain/notification/service/ShelterNotificationService.java, src/test/java/com/clova/anifriends/domain/notification/controller/ShelterNotificationControllerTest.java, src/test/java/com/clova/anifriends/domain/notification/repository/ShelterNotificationRepositoryTest.java, src/test/java/com/clova/anifriends/domain/notification/service/ShelterNotificationServiceTest.java
보호소 알림 읽음 처리 API 구현
- 해당 보호소의 안 읽음 알림들을 모두 읽음 처리하는 쿼리, 테스트 코드 작성
- 컨트롤러단, 서비스단 메서드 작성
- 테스트 코드 작성
- close #219
=> feat: 보호소 알림 읽음 처리 API를 구현한다. 

src/main/java/com/clova/anifriends/domain/chat/controller/ChatRoomController.java, src/main/java/com/clova/anifriends/domain/chat/dto/response/FindChatRoomIdResponse.java, src/main/java/com/clova/anifriends/domain/chat/repository/ChatRoomRepository.java, src/main/java/com/clova/anifriends/domain/chat/service/ChatRoomService.java, src/test/java/com/clova/anifriends/domain/chat/controller/ChatRoomControllerTest.java, src/test/java/com/clova/anifriends/domain/chat/service/ChatRoomServiceTest.java, src/test/java/com/clova/anifriends/domain/chat/support/ChatRoomFixture.java
채팅방ID를 조회하는 기능을 구현한다.
- 채팅방을 조회하는 레포지토리 구현
- 기존의 채팅방이 존재하면 chatRoomId, 존재하지 않는다면 null을 반환하는 서비스 및 컨트롤러 작성
- 서비스와 컨트롤러 테스트코드 작성
- close #201
=> feat: 채팅방ID를 조회하는 기능을 구현한다.

src/main/java/com/clova/anifriends/global/config/SecurityConfig.java, src/main/java/com/clova/anifriends/global/security/authorize/UnauthorizedEntryPoint.java, src/test/java/com/clova/anifriends/global/security/authorize/UnauthorizedEntryPointTest.java
- 스프링 시큐리티 역할 기반 api 필터링 시 접근 권한이 없는 경우의 응답 메시지를 커스터마이징하였습니다.
- UnauthorizedEntryPoint 구현 및 SecuriyConfig에 추가
- close #257
=> feat: 스프링 시큐리티 역할 기반 api 필터링 시 응답 메시지 내용을 커스텀한다.

src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterPassword.java, src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerPassword.java, src/main/java/com/clova/anifriends/global/exception/ErrorCode.java
- 프론트 요청에 따라 비밀번호 변경 시 발생할 수 있는 에러 코드를 추가했습니다.
- 비밀번호 변경 로직에서 추가한 에러코드를 적용하였습니다.
- ErrorCode 값 추가
- 비밀번호 변경 로직 수정
- close #256
=> feat: 비밀번호 변경 시 실패에 대한 에러코드를 추가한다.

src/docs/asciidoc/index.adoc, src/main/java/com/clova/anifriends/domain/chat/controller/ChatRoomController.java, src/main/java/com/clova/anifriends/domain/chat/repository/ChatMessageRepository.java, src/main/java/com/clova/anifriends/domain/chat/service/ChatRoomService.java, src/test/java/com/clova/anifriends/domain/chat/controller/ChatRoomControllerTest.java, src/test/java/com/clova/anifriends/domain/chat/repository/ChatMessageRepositoryTest.java, src/test/java/com/clova/anifriends/domain/chat/service/ChatRoomServiceTest.java
- 안 읽은 메시지 총 수 조회(보호소) 로직을 구현하였습니다.
- 안 읽은 메시지 총 수 조회(보호소) api, 서비스 로직 구현
- close #221
=> feat: 안읽은 메시지 총 개수를 조회한다.(보호소) 

src/main/java/com/clova/anifriends/domain/volunteer/controller/VolunteerController.java, src/test/java/com/clova/anifriends/domain/volunteer/controller/VolunteerControllerTest.java
- 보호소 비밀번호 변경 API 경로와 통일시키기 위해 봉사자 비밀번호 변경 API 경로를 수정했습니다. (프론트 요청사항)
- 봉사자 비밀번호 변경 API 경로를 수정했습니다.
- close #263
=> refactor: 봉사자 비밀번호 변경 API 경로를 수정한다.

src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java, src/main/java/com/clova/anifriends/domain/recruitment/dto/request/FindRecruitmentsByShelterRequest.java, src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryCustom.java, src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryImpl.java, src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java, src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java, src/test/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryTest.java, src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
보호소에서 하는 모집 검색 API에 마감 여부 필터링을 추가한다.
- requestDTO에 isClosed 추가
- service, controller, 쿼리 함수에 isClosed를 받게 한다.
- 쿼리 함수에서 isClosed 필터링 추가
- 관련 테스트 코드 수정
- close #253
=> feat: 보호소 모집 검색 API에서 마감 여부 필터링을 추가한다.

src/main/java/com/clova/anifriends/domain/recruitment/controller/KeywordCondition.java, src/main/java/com/clova/anifriends/domain/recruitment/controller/KeywordConditionByShelter.java, src/main/java/com/clova/anifriends/domain/recruitment/controller/KeywordFilter.java, src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java, src/main/java/com/clova/anifriends/domain/recruitment/dto/request/FindRecruitmentsByShelterRequest.java, src/main/java/com/clova/anifriends/domain/recruitment/dto/request/FindRecruitmentsRequest.java, src/test/java/com/clova/anifriends/domain/recruitment/controller/KeywordFilterTest.java, src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
- 봉사 모집글 조회 봉사자, 보호소 api의 검색 필터 파라미터를 enum 값으로 변경하였습니다.
- null이 입력으로 들어올 시 ALL 이라는 값을 반환하여 전체 검색이 수행될 수 있도록 했습니다.
- `KeywordFilter` 추가
- close #281
=> refactor: 봉사 모집글 조회 키워드 필터를 enum으로 변경한다.

src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentDetailResponse.java, src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepository.java, src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java, src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java, src/test/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryTest.java, src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
봉사 모집글 상세 조회 응답에 shelterId를 추가한다. 
- 봉사 모집글 상세 조회 JPQL 작성
- responseDTO에 shelterId 추가
- 테스트 코드 작성 및 수정
- close #290
=> feat: 봉사 모집글 상세 조회 API에 shelterId를 추가한다. 

src/main/java/com/clova/anifriends/domain/animal/controller/AnimalController.java, src/main/java/com/clova/anifriends/domain/animal/dto/FindAnimalsByVolunteerRequestV2.java, src/main/java/com/clova/anifriends/domain/animal/dto/response/FindAnimalsResponse.java, src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryCustom.java, src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryImpl.java, src/main/java/com/clova/anifriends/domain/animal/service/AnimalService.java, src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryImpl.java, src/test/java/com/clova/anifriends/domain/animal/controller/AnimalControllerTest.java, src/test/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryTest.java, src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceTest.java
- 보호동물 목록 정렬 기준인 `created_at`과 보호 동물의 PK인 `animal_id` 기반으로 no offset 페이지네이션 레포지토리 구현
- V2의 dto, service, controller 생성
- repository, service, controller 테스트코드 작성
- 보호동물 검색(봉사자) 로직의 페이지네이션을 커서 기반으로 개선했습니다.
- close #269
=> refactor: 보호동물 검색(봉사자) 로직의 페이지네이션을 커서 기반으로 개선한다.

.github/workflows/cd-dev.yml, build.gradle, src/main/java/com/clova/anifriends/domain/animal/controller/AnimalController.java, src/main/java/com/clova/anifriends/global/config/RedisConfig.java, src/test/java/com/clova/anifriends/AnifriendsApplicationTests.java, src/test/java/com/clova/anifriends/base/BaseControllerTest.java, src/test/java/com/clova/anifriends/base/config/RedisTestContainerConfig.java, src/test/resources/application.yml
- build.gradle에 redis 설정 및 testContainer 추가
- dev, prod, local yml 파일에 redis 설정 추가
- EC2에서 POST, GET 테스트 API 검증 완료
[POST] http://{ip}/api/data
[GET] http://{ip}/api/data?key=test
테스트 API는 검증 후 삭제했습니다.
- redis의 key, value 값에 따라 redisConfig 파일에 템플릿을 추가하고 사용하시면 됩니다.
dev 서버에 docker-compose를 이용한 redis 환경 설정
- close #298
=> chore: dev 서버에 docker-compose를 이용한 redis 환경을 설정한다.

src/main/java/com/clova/anifriends/domain/applicant/Applicant.java, src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantService.java, src/main/java/com/clova/anifriends/domain/recruitment/Recruitment.java, src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepository.java, src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java, src/main/java/com/clova/anifriends/domain/recruitment/vo/RecruitmentApplicantCount.java, src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantIntegrationTest.java, src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantServiceTest.java, src/test/java/com/clova/anifriends/domain/recruitment/support/fixture/RecruitmentFixture.java, src/test/java/com/clova/anifriends/domain/recruitment/vo/RecruitmentApplicantCountTest.java
- 봉사 신청 동시성 이슈 발생 지점에 비관적 락을 적용하였습니다.
- `@Lock(LockModeType.PESSIMISTIC_WRITE)`을 적용하였습니다.
- close #271
=> refactor: 봉사 신청 로직 동시성 이슈를 해결한다.

src/main/java/com/clova/anifriends/domain/auth/authentication/JwtAuthenticationProvider.java, src/main/java/com/clova/anifriends/global/config/SecurityConfig.java, src/main/java/com/clova/anifriends/global/security/jwt/JJwtProvider.java, src/main/java/com/clova/anifriends/global/web/filter/JwtAuthenticationExceptionHandler.java, src/main/java/com/clova/anifriends/global/web/filter/JwtAuthenticationFilter.java, src/test/java/com/clova/anifriends/global/web/filter/JwtAuthenticationExceptionHandlerTest.java
- JWT 인증 필터에서 발생하는 예외 핸들링을 추가하였습니다.
- 필터에서 예외가 발생한는 경우 cors가 적용되지 않는 문제를 수정하였습니다.
- cors 필터를 직접 추가하여 필터 순서를 변경하였습니다. cors 필터를 인증 필터와 인증 필터 예외 핸들러보다 앞단에 두어 항상 cors 필터를 거치도록 조정하였습니다.
- JWT 인증 예외 핸들러 필터 추가
- cors 설정 변경
- close #302
=> fix: 인증 필터 예외 핸들링을 추가한다.

src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepository.java
- `recruitment`의 `findRecruitmentsByShelter, findShelterRecruitmentsByShelter, findRecruitmentDetail, findCompletedRecruitments, findRecruitments, findRecruitmentsV2` 함수를 확인한 결과 `findRecruitmentDetail`에서 N + 1 문제가 발생했습니다. 이를 fetch join으로 해결했습니다.
- findRecruitmentDetail의 n+1 문제를 fetch join으로 해결
- #272
=> refactor: findRecruitmentDetail의 n+1 문제를 fetch join으로 해결한다.

src/main/java/com/clova/anifriends/domain/shelter/Shelter.java, src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java, src/main/java/com/clova/anifriends/domain/volunteer/VolunteerImage.java, src/test/java/com/clova/anifriends/domain/shelter/ShelterTest.java, src/test/java/com/clova/anifriends/domain/volunteer/VolunteerTest.java
- 봉사자, 보호소 프로필 이미지 수정 시 빈 문자열을 다루도록 개선하였습니다.
- imageUrl 반환 시 null 인 경우 null 대신 빈 문자열을 다루도록 개선하였습니다.
- 이미지 업데이트 시 null 이 입력된 경우 무시하고, 빈 문자열이 입력된 경우 기존 이미지를 삭제합니다.
- 봉사자, 보호소 이미지 업데이트 및 반환 로직 수정
- close #301
=> refactor: 프로필 이미지 수정 시 null 대신 빈 문자열을 다루도록 개선한다. 

src/main/java/com/clova/anifriends/domain/animal/controller/AnimalController.java, src/main/java/com/clova/anifriends/domain/chat/controller/ChatRoomController.java, src/main/java/com/clova/anifriends/domain/chat/dto/response/RegisterChatRoomResponse.java, src/main/java/com/clova/anifriends/domain/chat/service/ChatRoomService.java, src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java, src/main/java/com/clova/anifriends/domain/review/controller/ReviewController.java, src/main/java/com/clova/anifriends/domain/review/dto/response/RegisterReviewResponse.java, src/main/java/com/clova/anifriends/domain/review/service/ReviewService.java, src/main/java/com/clova/anifriends/domain/shelter/controller/ShelterController.java, src/main/java/com/clova/anifriends/domain/shelter/dto/response/RegisterShelterResponse.java, src/main/java/com/clova/anifriends/domain/shelter/service/ShelterService.java, src/main/java/com/clova/anifriends/domain/volunteer/controller/VolunteerController.java, src/main/java/com/clova/anifriends/domain/volunteer/dto/response/RegisterVolunteerResponse.java, src/main/java/com/clova/anifriends/domain/volunteer/service/VolunteerService.java, src/test/java/com/clova/anifriends/domain/animal/controller/AnimalControllerTest.java, src/test/java/com/clova/anifriends/domain/chat/controller/ChatRoomControllerTest.java, src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java, src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java, src/test/java/com/clova/anifriends/domain/shelter/controller/ShelterControllerTest.java, src/test/java/com/clova/anifriends/domain/shelter/service/ShelterIntegrationTest.java, src/test/java/com/clova/anifriends/domain/volunteer/controller/VolunteerControllerTest.java, src/test/java/com/clova/anifriends/domain/volunteer/service/VolunteerIntegrationTest.java
- 프론트엔드 요청에 따라 리소스 생성시 응답 메시지 바디에 리소스 ID를 반환하도록 변경하였습니다. 
- 봉사 모집글, 보호 동물, 리뷰, 채팅방, 봉사자, 보호소에 대하여 추가했습니다.
- 201 create 응답에 대해 응답 메시지 바디에 생성된 리소스 ID 추가
- close #310
=> feat: 리소스 생성시 응답 바디에 리소스 ID를 함께 반환하도록 변경한다. 

src/main/java/com/clova/anifriends/domain/animal/controller/AnimalController.java, src/main/java/com/clova/anifriends/domain/animal/dto/FindAnimalsByVolunteerRequestV2.java, src/main/java/com/clova/anifriends/domain/animal/dto/request/FindAnimalsByShelterRequest.java, src/main/java/com/clova/anifriends/domain/animal/dto/request/FindAnimalsByVolunteerRequest.java, src/test/java/com/clova/anifriends/domain/animal/controller/AnimalControllerTest.java, src/test/java/com/clova/anifriends/domain/animal/service/AnimalCacheServiceTest.java
보호 동물 목록 조회 dto 의 보호 동물 크기 파라미터명을 `animalSize` 로 변경한다.
- 보호 동물 목록 조회 dto 의 보호 동물 크기 파라미터명을 `animalSize` 로 변경
- 기존의 페이지 네이션 변수 명을 `pageNumber` -> `page`, `pageSize` -> `size` 로 변경
- close #315
=> fix: 보호 동물 목록 조회 dto 의 보호 동물 크기 파라미터명을 animalSize 로 변경한다.

src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryImpl.java, src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentCacheService.java, src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java, src/main/java/com/clova/anifriends/global/config/RedisConfig.java, src/test/java/com/clova/anifriends/base/BaseIntegrationTest.java, src/test/java/com/clova/anifriends/domain/animal/service/AnimalCacheServiceTest.java, src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceIntegrationTest.java, src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantIntegrationTest.java, src/test/java/com/clova/anifriends/domain/chat/service/ChatRoomIntegrationTest.java, src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentCacheServiceTest.java, src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentIntegrationTest.java, src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java, src/test/java/com/clova/anifriends/domain/review/service/ReviewIntegrationTest.java, src/test/java/com/clova/anifriends/domain/shelter/service/ShelterIntegrationTest.java, src/test/java/com/clova/anifriends/domain/volunteer/service/VolunteerIntegrationTest.java
- 봉사자 입장에서 모집글 검색 시 `Request Param에 아무 조건도 없을 때` count가 캐시에 있으면 캐시에서 가져옵니다.
- 캐시에 없으면 db에서 가져오고, 캐시에 count를 저장합니다.
- 봉사자 입장에서 모집글 등록 시 캐시에 recruitmentCount가 있다면 증가한다.
- 캐시에 없으면 db에서 가져오고, 캐시에 갱신된 count를 저장합니다.
- 봉사자 입장에서 모집글 삭제 시 캐시에 recruitmentCount가 있다면 캐시에 있는 값을 감소한다.
- 캐시에 없으면 db에서 가져오고, 캐시에 갱신된 count를 저장합니다.
- 봉사자 입장에서 모집글 검색, 등록, 삭제 시 캐시에서 데이터를 가져옵니다.
- close #314
=> refactor: 봉사자 입장에서 모집글 검색 시 count를 캐시에 저장한다.

src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentsResponse.java, src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentCacheRepository.java, src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentCacheService.java, src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java, src/main/java/com/clova/anifriends/global/config/RedisConfig.java, src/main/java/com/clova/anifriends/global/event/CacheWarmer.java, src/test/java/com/clova/anifriends/base/BaseIntegrationTest.java, src/test/java/com/clova/anifriends/base/TestContainerStarter.java, src/test/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentCacheRepositoryTest.java, src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentCacheServiceTest.java, src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java, src/test/java/com/clova/anifriends/domain/recruitment/support/fixture/RecruitmentFixture.java, src/test/resources/application.yml
- 봉사 모집글 목록 첫 페이지를 캐싱하도록 로직을 구현하였습니다.
- 레디스 접근을 영속성 계층에서 발생하는 일이라 판단하여 RecruitmentCacheRepository로 이름지었습니다.
- 20개를 초과하는 요청이 들어오는 경우 20개까지의 데이터를 캐싱해서 반환합니다.
- 30개의 데이터를 캐싱하며 만일 캐싱된 데이터가 20개 이하인 경우 캐시 데이터를 신뢰하지 않고 db에서 조회를 수행합니다.
- 봉사 모집글이 생성, 수정, 삭제 되는 경우 캐시 데이터를 갱신합니다.
- 웜업의 경우 다른 캐시 로직이 머지된 후 추가하겠습니다.
- RecruitmentCacheRepository 추가
- 봉사 모집글 생성, 업데이트, 삭제 시 캐시 갱신
- 봉사 모집글 목록 조회 시 캐시 데이터 이용
- close #309
=> refactor: 봉사 모집글 목록을 캐싱하여 응답 속도를 개선한다.

src/main/java/com/clova/anifriends/domain/auth/controller/AuthController.java, src/main/java/com/clova/anifriends/global/exception/ErrorCode.java, src/test/java/com/clova/anifriends/domain/auth/controller/AuthControllerTest.java
- 리프레시 토큰이 존재하지 않는 경우의 적절한 예외 처리를 추가하였습니다.
- 해당 상황에 대한 에러 코드를 추가하고 401 응답이 나가도록 구현하였습니다.
- 리프레시 토큰 쿠키에 secure 설정과 발급받은 도메인을 명시하였습니다.
- 리프레시 토큰 쿠키가 없는 경우에 대한 예외 처리 추가
- close #317
=> fix: 리프레시 토큰이 존재하지 않는 경우에 대한 예외를 추가한다. 

src/main/java/com/clova/anifriends/global/config/SecurityConfig.java, src/test/resources/application.yml
- 서브모듈에 front.volunteer.server를 추가했습니다.
- 서브모듈에서 기존에 front.server (보호소 주소)를 front.shelter.server로 변경했습니다.
- 프론트 봉사자 배포 주소 추가
- close #341
=> chore: 프론트 봉사자 배포 주소를 추가한다.

src/main/java/com/clova/anifriends/domain/applicant/controller/ApplicantController.java, src/main/java/com/clova/anifriends/domain/applicant/dto/response/FindApplyingVolunteersResponse.java, src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java, src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantService.java, src/main/java/com/clova/anifriends/domain/applicant/vo/ApplicantStatus.java, src/main/java/com/clova/anifriends/domain/volunteer/repository/VolunteerRepository.java, src/test/java/com/clova/anifriends/domain/applicant/controller/ApplicantControllerTest.java, src/test/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepositoryTest.java, src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantServiceTest.java
- 봉사자가 신청한 봉사 리스트 조회 API를 Pagenation 방식으로 변경했습니다.
- 봉사자가 신청한 봉사 리스트 조회를 pagination 방식으로 변경
- close #357
=> refactor: 봉사자가 신청한 봉사 리스트 조회를 pagination 방식으로 변경한다.

src/main/java/com/clova/anifriends/domain/animal/Animal.java, src/main/java/com/clova/anifriends/domain/animal/dto/response/FindAnimalsResponse.java, src/main/java/com/clova/anifriends/domain/animal/repository/AnimalCacheRepository.java, src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepository.java, src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryCustom.java, src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryImpl.java, src/main/java/com/clova/anifriends/domain/animal/repository/response/FindAnimalsResult.java, src/main/java/com/clova/anifriends/domain/animal/service/AnimalService.java, src/test/java/com/clova/anifriends/domain/animal/controller/AnimalControllerTest.java, src/test/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryTest.java, src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceIntegrationTest.java, src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceTest.java, src/test/java/com/clova/anifriends/domain/animal/support/fixture/AnimalDtoFixture.java
보호 동물 조회 api 에서 발생한 N+1 문제를 해결했습니다.
- `findAnimalDetail` 의 `AnimalImages` 에 `fetch join` 적용
- `findAnimalsByShelter` 의 `AnimalImages` 콜렉션에 `BatchSize` 설정
- `findAnimalsByVolunteerV2` 에 `DTO Projection` 적용
- close #272
=> refactor: 보호 동물 조회 api 에서 발생한 N+1 문제를 해결한다.

nginx/nginx.conf
- nginx에 파일 용량 제한을 2.5GB로 늘린다.
- nginx에 파일 용량 제한을 2.5GB로 늘린다.
- close #369
=> feat: nginx에 파일 용량 제한을 늘린다.

src/main/java/com/clova/anifriends/domain/applicant/Applicant.java, src/main/java/com/clova/anifriends/domain/applicant/exception/ApplicantCanNotApplyException.java, src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantService.java, src/test/java/com/clova/anifriends/domain/applicant/ApplicantTest.java, src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantIntegrationTest.java
- ApplicantConcurrencyException -> ApplicantCanNotApplyException으로 변경
- 모집 마감된 봉사일 때 ApplicantCanNotApplyException을 던지게 변경
- 모집 마감된 봉사 신청 시 응답 상태 코드를 수정
- close #376
=> fix: 모집 마감된 봉사 신청 시 응답 상태 코드를 수정한다.

src/docs/asciidoc/index.adoc, src/main/java/com/clova/anifriends/domain/auth/controller/AuthController.java, src/main/resources/static/docs/index.html, src/test/java/com/clova/anifriends/domain/auth/controller/AuthControllerTest.java, src/test/java/com/clova/anifriends/domain/auth/support/AuthFixture.java
- 기존 액세스 토큰 갱신 api가 보호소, 봉사자가 공유하기에 적절하지 않아 분리하였습니다.
- 서로 다른 이름의 쿠키가 응답으로 나가기 때문에 로그아웃 API 역시 분리하였습니다.
- 봉사자, 보호소 액세스 토큰 갱신 API, 로그아웃 API 추가
- close #378
=> feat: 봉사자, 보호소 액세스 토큰 갱신 api를 분리한다.

src/main/java/com/clova/anifriends/domain/volunteer/dto/response/FindVolunteerMyPageResponse.java
- FindVolunteerMyPageResponse에서 status가 ATTENDENCE이고 현재 시간이 시작 시간 이후여야 봉사 완료 횟수가 증가하도록 수정
- 봉사자가 봉사 신청 후 보호소가 승인할 경우 봉사자의 봉사 완료 횟수가 증가하는 버그를 해결한다.
- close #384
=> fix: 봉사자가 봉사 신청 후 보호소가 승인할 경우 봉사자의 봉사 완료 횟수가 증가하는 버그를 해결한다.

src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryImpl.java
내(보호소)가 작성한 봉사 모집글 검색 시 키워드 검색이 되지 않는 문제를 수정한다.
`RecruitmentRepositoryImpl`에서 `getKeywordCondition` 메서드 수정
- close #386
=> fix: 내(보호소)가 작성한 봉사 모집글 검색 시 키워드 검색이 되지 않는 문제를 수정한다.

src/main/java/com/clova/anifriends/domain/review/Review.java, src/test/java/com/clova/anifriends/domain/review/service/ReviewIntegrationTest.java
- 리뷰 이미지 업데이트 시 이미지 컬렉션에 대한 참조를 변경하지 않도록 수정하였습니다.
- 리뷰 업데이트에 대한 통합 테스트를 추가하였습니다.
- 리뷰 업데이트 로직 수정
- close #392
=> fix: 리뷰 업데이트 시 이미지 컬렉션에 대한 참조를 변경하지 않도록 수정한다.

src/main/java/com/clova/anifriends/domain/applicant/controller/ApplicantController.java, src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantService.java, src/main/java/com/clova/anifriends/domain/recruitment/dto/response/IsAppliedRecruitmentResponse.java, src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryImpl.java, src/test/java/com/clova/anifriends/domain/applicant/controller/ApplicantControllerTest.java, src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantServiceTest.java, src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentIntegrationTest.java
- 봉사 모집글 목록 조회 v1, v2 쿼리에 페치 조인을 적용하여 n+1 문제를 개선하였습니다.
- 봉사 모집글 목록 조회 페치 조인 적용
- close #366
=> refactor: 봉사 모집글 목록 조회 쿼리를 개선한다.

src/main/java/com/clova/anifriends/domain/review/controller/ReviewController.java, src/main/java/com/clova/anifriends/domain/review/dto/request/RegisterReviewRequest.java, src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
- 리뷰 등록 API 요청 dto의 변수명 중 API 명세와 다른 부분이 있어 이를 수정하였습니다.
- `RegisterReviewRequest`의 인스턴스 변수명 수정
- close #396
=> fix: 리뷰 등록 api 요청 변수 이름을 수정한다. 

src/main/java/com/clova/anifriends/domain/notification/service/ShelterNotificationService.java, src/main/java/com/clova/anifriends/domain/notification/service/VolunteerNotificationService.java, src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java, src/main/java/com/clova/anifriends/global/scheduler/NotifyScheduler.java, src/main/java/com/clova/anifriends/global/scheduler/ServiceScheduler.java, src/test/java/com/clova/anifriends/base/BaseIntegrationTest.java, src/test/java/com/clova/anifriends/base/BaseSchedulerTest.java, src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceIntegrationTest.java, src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentIntegrationTest.java, src/test/java/com/clova/anifriends/domain/review/service/ReviewIntegrationTest.java, src/test/java/com/clova/anifriends/global/scheduler/NotifySchedulerTest.java, src/test/java/com/clova/anifriends/global/scheduler/ServiceSchedulerTest.java, src/test/resources/application.yml
- 테스트를 위한 스케줄러 표현식을 매초 실행으로 변경하였습니다.
- 스케줄러와 서비스 로직을 분리하였습니다. 이에 맞춰 새로운 테스트 클래스를 생성하였습니다.
- 스케줄러 행위 테스트를 위한 `BaseSchedulerTest`를 생성하였습니다. 새롭게 생성한 스케줄러 클래스 테스트는 이를 사용합니다. 스케줄러 애플리케이션 컨텍스트 초기화 횟수가 기존 2개 -> 1개로 감소하였습니다.
- S3Service mock을 `BaseIntegrationTest`로 이동시켰습니다.
- 컨텍스트 초기화 횟수를 8회 -> 6회로 감소시켰습니다. 테스트 시간이 약 17초에서 12초로 감소하였습니다.
- 스케줄링, 서비스 로직 분리
- `BaseSchedulerTest` 추가
- 테스트 시 `S3Service` MockBean 선언 위치 변경
- close #387
=> refactor: 테스트 시 애플리케이션 컨텍스트 초기화를 줄여 테스트 속도를 개선한다.

src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepository.java, src/test/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryTest.java
봉사 모집 조회 시 이미지를 left join 하도록 수정한다.
봉사 모집 조회 시 이미지를 left join 하도록 수정한다.
- close #399
=> fix: 봉사 모집 조회 시 이미지를 left join 하도록 수정한다.

src/main/java/com/clova/anifriends/global/image/S3Service.java
- 크롭된 이미지 형식이 `.webp` 형식이라 추가했습니다.
- 이미지 확장자에 .webp를 추가
- close #401
=> fix: 이미지 확장자에 .webp를 추가한다.

src/main/java/com/clova/anifriends/domain/review/dto/response/FindShelterReviewsByShelterResponse.java, src/main/java/com/clova/anifriends/domain/review/repository/ReviewRepository.java, src/main/java/com/clova/anifriends/domain/review/repository/response/FindShelterReviewResultV2.java, src/main/java/com/clova/anifriends/domain/review/service/ReviewService.java, src/main/java/com/clova/anifriends/domain/volunteer/VolunteerImage.java, src/test/java/com/clova/anifriends/domain/review/repository/ReviewRepositoryTest.java, src/test/java/com/clova/anifriends/domain/review/service/ReviewServiceTest.java
- 프로젝션으로 조회하던 것을 엔티티를 조회해오도록 수정하였습니다.
- 현재 reviewCount 조회 시 n+1 문제가 발생하여 최적화가 필요합니다.
- 내(보호소)가 받은 리뷰 목록 조회 프로젝션에서 엔티티 조회로 변경
- close #405
=> fix: 내(보호소)가 받은 리뷰 목록 조회시 데이터 조회가 되지 않는 문제를 수정한다.

src/main/java/com/clova/anifriends/domain/review/dto/response/FindShelterReviewsByShelterResponse.java, src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java, src/test/java/com/clova/anifriends/domain/review/service/ReviewServiceTest.java
- FindShelterReviewResponse의 VolunteerReviewCount를 volunteerReviewCount로 변경한다.
- FindShelterReviewResponse에서 VolunteerReviewCount 이름을 수정한다.
- close #411
=> fix: FindShelterReviewResponse에서 VolunteerReviewCount 이름을 수정한다.

src/main/java/com/clova/anifriends/domain/applicant/Applicant.java, src/main/java/com/clova/anifriends/domain/review/repository/ReviewRepository.java, src/main/java/com/clova/anifriends/domain/review/service/ReviewService.java, src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java, src/main/java/com/clova/anifriends/domain/volunteer/vo/VolunteerReviewCount.java, src/test/java/com/clova/anifriends/base/BaseIntegrationTest.java, src/test/java/com/clova/anifriends/domain/review/service/ReviewIntegrationTest.java, src/test/java/com/clova/anifriends/domain/review/service/ReviewServiceTest.java, src/test/java/com/clova/anifriends/domain/volunteer/vo/VolunteerReviewCountTest.java
- 봉사자가 작성한 봉사 후기 개수에 대한 정보를 반정규화하였습니다.
- 후기 작성, 삭제 시에 증감하는 로직을 추가하였습니다.
- 내(보호소)가 받은 봉사 후기 목록 조회 시 n+1을 제거하였습니다.
- 봉사자가 작성한 봉사 후기 개수(`VolunteerReviewCount`) vo 추가
- close #415
=> refactor: 봉사자가 작성한 후기 개수를 반정규화한다.

src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentDetailResponse.java, src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentsByShelterResponse.java, src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentsResponse.java, src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentCacheRepository.java, src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepository.java, src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java, src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java, src/test/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentCacheRepositoryTest.java, src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentIntegrationTest.java, src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
- 봉사 모집글 자동 만료 스케줄링 간격을 하루에 한번에서 매분마다로 변경하였습니다.
- 봉사 모집글 자동 만료 로직을 일부 수정하였습니다.
- 봉사 모집글 자동 만료 스케줄링 크론 표현식 수정
- 해당 로직 일부 수정
- close #419
=> fix: 봉사 모집글 만료 스케줄링 간격을 수정한다.

src/main/java/com/clova/anifriends/domain/review/repository/ReviewRepository.java, src/test/java/com/clova/anifriends/domain/review/service/ReviewIntegrationTest.java
- 내(보호소)가 받은 리뷰 목록 조회 쿼리가 컬렉션을 left join 하지 않도록 변경하였습니다.
- batchSize가 정상 적용되는 것을 확인하였습니다.
- 내(보호소)가 받은 리뷰 목록 조회 쿼리 수정
- close #421
=> fix: 내(보호소)가 받은 리뷰 목록 조회 batchSize가 적용되지 않는 문제를 수정한다.

src/main/java/com/clova/anifriends/global/aspect/DataIntegrityAspect.java, src/main/java/com/clova/anifriends/global/aspect/LogAspect.java, src/test/resources/application.yml
- `DataIntegrityAspect`, `LogAspect` 의 순서 설정
- `DataIntegrityAspect` 는 @Order(1) 로 설정
- `LogAspect` 는 @Order(2) 로 설정
- close #436
=> refactor: AOP 순서를 지정한다.

src/main/java/com/clova/anifriends/domain/shelter/Shelter.java, src/main/java/com/clova/anifriends/domain/shelter/ShelterImage.java, src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java, src/main/java/com/clova/anifriends/domain/volunteer/VolunteerImage.java, src/test/java/com/clova/anifriends/domain/shelter/service/ShelterIntegrationTest.java, src/test/java/com/clova/anifriends/domain/volunteer/service/VolunteerIntegrationTest.java
- OneToOne 연관관계를 갖는 volunteer / volunteer_image, shelter/shelter_image 의 외래키를 주테이블에서 관리하도록 수정 (프로필 이미지의 경우, 항상 주테이블인 volunteer 나 shelter 를 통해 접근하기 때문에 외래키를 주테이블에서 관리하도록 수정하는게 옳은 방향이라 생각했습니다.)
1. 봉사자나 보호소가 프로필 수정을 하면 flush 될 때 새로운 이미지의 insert 쿼리가 먼저 실행되어 volunteer_id FK unique 제약 조건 위반 예외가 발생하였습니다. FK 를 주 테이블인 volunteer / shelter 가 관리하도록 설정하여 다음과 같이 `새로운 image insert` -> `기존의 주 테이블 update` -> `기존의 image delete` 로 실행되도록 수정하였습니다.
2. 연관관계가 제거될 시 image 가 함께 삭제되도록 `orphanRemoval = true` 를 설정하였습니다.
- close #424
=> fix: 봉사자 이미지 업데이트 시 기존 이미지 엔티티가 제거되지 않는 문제를 수정한다.

src/main/java/com/clova/anifriends/domain/common/event/ImageDeletionListener.java, src/main/java/com/clova/anifriends/global/config/AsyncConfig.java, src/test/java/com/clova/anifriends/base/BaseIntegrationTest.java, src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceIntegrationTest.java, src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentIntegrationTest.java, src/test/java/com/clova/anifriends/domain/review/service/ReviewIntegrationTest.java
- `@Async` 를 사용하여 S3 이미지 삭제 로직이 비동기적으로 동작하도록 수정
- `ImageDeletionEvent` 에 적용할 `asyncImageRemoverExecutor` 설정
- `@RecordApplicationEvents` 를 사용하여 비동기 이벤트 호출 여부 테스트
- close #444
=> refactor: S3 에서 이미지를 삭제하는 로직을 비동기적으로 동작하도록 수정한다.

src/main/java/com/clova/anifriends/domain/applicant/dto/response/FindApprovedApplicantsResponse.java, src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java, src/main/java/com/clova/anifriends/domain/applicant/repository/response/FindApprovedApplicantsResult.java, src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantMapper.java, src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantService.java, src/test/java/com/clova/anifriends/domain/applicant/ApplicantTest.java, src/test/java/com/clova/anifriends/domain/applicant/controller/ApplicantControllerTest.java, src/test/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepositoryTest.java, src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantServiceTest.java, src/test/java/com/clova/anifriends/domain/applicant/support/ApplicantDtoFixture.java
- `ApplicantRepository의 findApprovedApplicants` 쿼리를 `dto`에 맞게 변경 & 결과를 `List<FindApprovedApplicantsResult>`로 변경했습니다.
- `Applicant의 isAttendance`를 사용하지 못해서 `ApplicantMapper의 resultToResponse에서 검증`하는 로직을 적용했습니다. (해당 인자가 Applicant에서 FindApprovedApplicantsResult로 변경되었기 때문입니다.)
- ApplicantDtoFixture에 FindApprovedApplicantsResult를 추가했습니다.
- `봉사자, 보호소 프론트 url을 변경`했습니다.
- 이슈/해결 아카이빙의 n+1 개선기 findApplicantsApproved 부분 업데이트했습니다.
- ApplicantRepository의 findApprovedApplicants 쿼리를 dto에 맞게 변경
- 봉사자, 보호소 프론트 url 변경
- close #398
=> refactor: findApprovedApplicants의 N+1 쿼리를 개선한다.

src/main/java/com/clova/anifriends/domain/donation/exception/DonationDuplicateException.java, src/main/java/com/clova/anifriends/domain/donation/repository/DonationCacheRepository.java, src/main/java/com/clova/anifriends/domain/donation/repository/DonationRedisRepository.java, src/main/java/com/clova/anifriends/domain/donation/service/DonationService.java, src/test/java/com/clova/anifriends/base/DatabaseCleaner.java, src/test/java/com/clova/anifriends/domain/donation/service/DonationIntegrationTest.java, src/test/java/com/clova/anifriends/domain/donation/service/DonationServiceTest.java
- Redis 의 String 자료구조와 TTL 을 사용하여 후원 API 중복 요청을 방지하였습니다.
- 후원 API 요청 시 Redis 에 `donation:{volunteerId}` : `true` 저장
- TTL 을 1초로 설정하여 1초 후 저장한 값 삭제
- 1초 내의 중복 요청 시 `DonationDuplicateException` 발생
- 독립적인 테스트를 위해 `DatebaseCleaner` 에 Redis 초기화 수행
- close #446
=> refactor: 후원 API 중복 요청을 방지한다. (따닥 방지)
