.github/workflows/ci.yml
build.gradle

- 코드 품질 관리를 위한 소나클라우드와 테스트 커버리지를 관리하기 위한 자코코를 추가하였습니다.
- ci 워크플로우 수정
- `build.gradle`에 플러그인 및 설정 추가
- close #1

chore: 소나클라우드와 프로젝트를 연결한다.

---

src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepository.java
src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java
src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepository.java
src/main/java/com/clova/anifriends/domain/review/repository/ReviewRepository.java
src/main/java/com/clova/anifriends/domain/shelter/repository/ShelterRepository.java
src/main/java/com/clova/anifriends/domain/volunteer/repository/VolunteerRepository.java

repository 를 구현한다.
repository 를 구현한다.
- close #23

feat: repository 를 구현한다.

---

src/main/java/com/clova/anifriends/global/exception/AniFriendsException.java
src/main/java/com/clova/anifriends/global/exception/AuthenticationException.java
src/main/java/com/clova/anifriends/global/exception/AuthorizationException.java
src/main/java/com/clova/anifriends/global/exception/BadRequestException.java
src/main/java/com/clova/anifriends/global/exception/ConflictException.java
src/main/java/com/clova/anifriends/global/exception/ErrorCode.java
src/main/java/com/clova/anifriends/global/exception/ErrorResponse.java
src/main/java/com/clova/anifriends/global/exception/GlobalExceptionHandler.java
src/main/java/com/clova/anifriends/global/exception/NotFoundException.java
src/test/java/com/clova/anifriends/global/exception/ExceptionController.java

Exception에 ErrorCode를 추가한다. 
- `ErrorCode` enum 파일 생성
- `AniFriendsException` 최상위 예외 클래스 생성  
- 모든 예외가 `AniFriendsException` 클래스를 상속받게 함.
- `ErrorResponse`에 ErrorCode 추가
- `GlobalExceptionHandler`에 errorCode 추가
- close #39

feat: Exception에 예외코드를 추가한다. 

---

src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java
src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindShelterByVolunteerReviewResponse.java
src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindShelterSimpleResponse.java
src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java

- 봉사 후기 작성시 보호소 정보 조회 로직 구현
- 봉사 후기 작성시 보호소 정보 조회 테스트 코드 작성
- 봉사 후기 작성시 보호소 정보 조회 로직 관련 서비스, 컨트롤러 코드 작성
- close #70

feat: 봉사 후기 작성시 보호소 정보 조회 로직을 구현한다.

---

src/main/java/com/clova/anifriends/domain/volunteer/controller/VolunteerController.java
src/main/java/com/clova/anifriends/domain/volunteer/service/VolunteerService.java
src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerPhoneNumber.java
src/test/java/com/clova/anifriends/domain/auth/service/AuthServiceTest.java
src/test/java/com/clova/anifriends/domain/volunteer/VolunteerTest.java
src/test/java/com/clova/anifriends/domain/volunteer/controller/VolunteerControllerTest.java
src/test/java/com/clova/anifriends/domain/volunteer/service/VolunteerServiceTest.java
src/test/java/com/clova/anifriends/domain/volunteer/support/VolunteerDtoFixture.java
src/test/java/com/clova/anifriends/domain/volunteer/support/VolunteerFixture.java
src/test/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerPhoneNumberTest.java

- controller에서 service로 인자를 보낼 때 RequestDTO 자체로 보내지 않는다.
- 사용자의 전화번호는-를 포함한다.
- controller, service, 관련 테스트 코드 수정
- 전화번호 validation 수정, 관련 테스트 코드 수정
- close #80

fix: controller에서 service로 인자를 보낼 때 RequestDTO 자체로 보내지 않는다. 

---

.github/workflows/CD.yml
.github/workflows/ci.yml
.github/workflows/sonar-cloud.yml
.gitignore
.gitmodules
scripts/deploy.sh
src/main/resources/application.yml
src/test/java/com/clova/anifriends/AnifriendsApplicationTests.java
src/test/java/com/clova/anifriends/base/BaseIntegrationTest.java

- 프로젝트의 민감정보를 관리하기 위한 서브모듈을 적용하였습니다.
- 깃허브 액션 워크플로우에도 해당 사항을 적용하였습니다.
- aws에 정상 배포되는지 여부를 확인할 필요가 있습니다.
- application.yml을 관리할 git submodule 적용
- close #96

chore: 서브모듈을 적용하여 민감정보를 관리한다.

---

src/docs/asciidoc/index.adoc
src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java
src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java

- 변경된 Location 헤더를 반영하였습니다.
- API 문서화를 추가하였습니다.
- index.adoc에 문서화 추가
- Location 헤더 변경
- close #134

refactor: 봉사 모집글 등록(보호소)를 명세에 맞게 수정한다.

---

src/main/java/com/clova/anifriends/domain/volunteer/dto/response/FindVolunteerProfileResponse.java
src/main/resources/static/docs/index.html
src/test/java/com/clova/anifriends/domain/auth/service/AuthServiceTest.java
src/test/java/com/clova/anifriends/domain/volunteer/controller/VolunteerControllerTest.java

응답 필드명을 명세에 맞게 수정한다.
봉사자 프로필 조회(공통)를 명세에 맞게 수정한다. 
- close #121

refactor: 봉사자 프로필 조회(공통)를 명세에 맞게 수정한다. 

---

src/main/java/com/clova/anifriends/domain/applicant/dto/FindApplicantsApprovedResponse.java

응답 필드명을 수정한다.
응답 필드명을 수정한다.
- close #136

refactor: 봉사 승인자 리스트 조회(보호소)를 명세에 맞게 수정한다.

---

build.gradle
src/docs/asciidoc/index.adoc
src/main/resources/static/docs/index.html
src/test/java/com/clova/anifriends/domain/auth/service/AuthServiceTest.java

- `./gradlew clean build` 시 `/docs/index.htm`에 접근할 수 없는 문제가 있었습니다.
- 정적 파일이 만들어지기 전에 build 하여 발생하는 문제로 보이나 해결하지 못했습니다.
- 임시로 문서화 후 pr 하시기 전에 로컬에서 build를 한 번 씩 돌려 index.html을 최신화 한 후 함께 pr 해주시기 바랍니다.
- 문서화 양식을 추가하였습니다.
- 문서화 양식 추가
- close #147

fix: 배포시 restDocs 정적 문서에 접근할 수 없는 문제를 해결한다.

---

src/docs/asciidoc/index.adoc
src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentsByVolunteerResponse.java
src/main/resources/static/docs/index.html
src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java

- 명세에 맞게 변수명을 수정했습니다.
- 문서화를 추가하였습니다.
- close #130

refactor: 모집글 검색(봉사자)를 명세에 맞게 수정한다. 

---

src/main/java/com/clova/anifriends/domain/review/dto/response/FindReviewResponse.java
src/test/java/com/clova/anifriends/domain/applicant/controller/ApplicantControllerTest.java
src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java

응답 필드를 수정했습니다.
- 불필요한 응답 필드 제거
- 필드명 수정
- 컨트롤러 테스트코드 수정
- close #128

refactor: 봉사 후기 상세 조회(봉사자)를 명세에 맞게 수정한다.

---

src/docs/asciidoc/index.adoc
src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindCompletedRecruitmentsResponse.java
src/main/resources/static/docs/index.html
src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java

- api 응답을 명세에 맞게 개선했습니다.
- 문서화를 추가하였습니다.
- close #124

refactor: 봉사자가 완료한 봉사 모집글 리스트 조회(공통)을 명세에 맞게 수정한다. 

---

src/docs/asciidoc/index.adoc
src/main/java/com/clova/anifriends/domain/animal/controller/AnimalController.java
src/main/java/com/clova/anifriends/domain/animal/dto/response/FindAnimalDetail.java
src/main/java/com/clova/anifriends/domain/animal/service/AnimalService.java
src/main/resources/static/docs/index.html
src/test/java/com/clova/anifriends/domain/animal/controller/AnimalControllerTest.java
src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceTest.java
src/test/java/com/clova/anifriends/domain/animal/support/fixture/AnimalDtoFixture.java

- 권한에 따른 보호 동물 상세를 하나의 api로 합쳤습니다.
- 명세에 따라 응답 변수명을 변경하였습니다.
- 문서화를 추가했습니다.
- close #123

refactor: 보호동물 상세(공통)를 명세에 맞게 수정한다. 

---

src/docs/asciidoc/index.adoc
src/main/java/com/clova/anifriends/domain/review/controller/ReviewController.java
src/main/java/com/clova/anifriends/domain/review/dto/response/FindShelterReviewsByShelterResponse.java
src/main/java/com/clova/anifriends/domain/review/service/ReviewService.java
src/main/resources/static/docs/index.html
src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
src/test/java/com/clova/anifriends/domain/review/service/ReviewServiceTest.java

- 보호소의 후기 리스트 조회(보호소) api 응답을 명세에 맞게 수정했습니다.
- 문서화를 추가하였습니다.
- close #120

refactor: 보호소에 달린 후기 리스트 조회(보호소)를 명세에 맞게 수정한다.

---

src/main/java/com/clova/anifriends/global/config/S3Config.java
src/main/java/com/clova/anifriends/global/image/S3Service.java
src/test/java/com/clova/anifriends/global/image/S3ServiceTest.java

S3 이미지 삭제 서비스를 구현했습니다.
- S3 이미지 삭제 로직 구현 및 테스트 코드 작성
- S3 테스트의 불필요한 stubbing 제거
- close #118

feat: S3 이미지 삭제 서비스를 구현한다.

---

src/main/java/com/clova/anifriends/global/config/WebMvcConfig.java
src/main/resources/application.yml

http://localhost:3000/ 에서 테스트 했을 때 잘 동작한걸로 보아 프론트 url에서도 문제 없을 것 같습니다.
- cors 설정 추가
- front 서버 링크 추가
- cors 설정 추가
- close #188

chore: cors 설정을 추가한다.

---

src/main/resources/application.yml
src/test/resources/application.yml

- RDS 인스턴스와 연동하기 위한 프로필을 수정 및 추가하였습니다.
- 로컬에서는 기존과 동일한 인메모리 DB로 동작합니다.
- 개발, 프로덕션에서는 RDS와 연동하기 위해 데이터소스를 수정하였습니다.
- application.yml 프로필 추가
- close #196

chore: AWS RDS 연동을 진행한다.

---

src/docs/asciidoc/index.adoc
src/main/java/com/clova/anifriends/domain/animal/Animal.java
src/main/java/com/clova/anifriends/domain/animal/controller/AnimalController.java
src/main/java/com/clova/anifriends/domain/animal/service/AnimalService.java
src/main/resources/static/docs/index.html
src/test/java/com/clova/anifriends/domain/animal/AnimalTest.java
src/test/java/com/clova/anifriends/domain/animal/controller/AnimalControllerTest.java
src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceIntegrationTest.java
src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceTest.java

- 보호 동물 삭제 api를 구현하였습니다.
- 보호 동물 삭제 api, 서비스 로직을 구현
- close #189

feat: 보호 동물 삭제 API를 구현한다.

---

src/docs/asciidoc/index.adoc
src/main/java/com/clova/anifriends/domain/review/Review.java
src/main/java/com/clova/anifriends/domain/review/controller/ReviewController.java
src/main/java/com/clova/anifriends/domain/review/service/ReviewService.java
src/main/resources/static/docs/index.html
src/test/java/com/clova/anifriends/base/BaseIntegrationTest.java
src/test/java/com/clova/anifriends/domain/review/ReviewTest.java
src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
src/test/java/com/clova/anifriends/domain/review/service/ReviewIntegrationTest.java
src/test/java/com/clova/anifriends/domain/review/service/ReviewServiceTest.java

- 봉사 후기 삭제 api를 구현하였습니다.
- 봉사 후기 삭제 api, 서비스 로직 구현
- close #194

feat: 봉사 후기 삭제 API를 구현한다.

---

src/docs/asciidoc/index.adoc
src/main/java/com/clova/anifriends/domain/recruitment/Recruitment.java
src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java
src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
src/main/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentInfo.java
src/main/resources/static/docs/index.html
src/test/java/com/clova/anifriends/base/BaseIntegrationTest.java
src/test/java/com/clova/anifriends/domain/recruitment/RecruitmentTest.java
src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentIntegrationTest.java
src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
src/test/java/com/clova/anifriends/domain/recruitment/support/fixture/RecruitmentFixture.java
src/test/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentInfoTest.java

- 봉사 모집글 삭제 api를 구현하였습니다.
- 삭제 가능 시간을 시작 시간 전 36시간 이전까지로 설정하였습니다.
- 봉사 모집글 삭제 api, 서비스 로직 구현
- close #191

feat: 봉사 모집글 삭제 API를 구현한다.

---

build.gradle
src/main/java/com/clova/anifriends/domain/chat/ChatMessage.java
src/main/java/com/clova/anifriends/domain/chat/ChatRoom.java
src/main/java/com/clova/anifriends/domain/chat/controller/ChatController.java
src/main/java/com/clova/anifriends/domain/chat/controller/ChatMessageController.java
src/main/java/com/clova/anifriends/domain/chat/controller/ChatRoomController.java
src/main/java/com/clova/anifriends/domain/chat/repository/ChatMessageRepository.java
src/main/java/com/clova/anifriends/domain/chat/repository/ChatRoomRepository.java
src/main/java/com/clova/anifriends/domain/chat/service/ChatService.java
src/main/java/com/clova/anifriends/global/config/WebSocketConfig.java
src/test/java/com/clova/anifriends/base/BaseControllerTest.java
src/test/java/com/clova/anifriends/base/BaseRepositoryTest.java

채팅 관련 Entity, Controller, Service, Repository 를 생성했습니다.
- 채팅 관련 Entity, Controller, Service, Repository 를 생성
- webSocket 의존성 추가 및 config 설정
- close #215

feat: 채팅 관련 Entity, Controller, Service, Repository 를 생성한다.

---

src/main/java/com/clova/anifriends/domain/chat/controller/ChatMessageController.java
src/main/java/com/clova/anifriends/domain/chat/controller/ChatMessageResponse.java
src/main/java/com/clova/anifriends/domain/chat/dto/request/ChatMessageRequest.java
src/main/java/com/clova/anifriends/domain/chat/dto/response/NewChatMessageResponse.java
src/main/java/com/clova/anifriends/domain/chat/service/ChatMessageService.java
src/test/java/com/clova/anifriends/domain/chat/controller/WebSocketStompTest.java
src/test/java/com/clova/anifriends/domain/chat/service/ChatMessageServiceTest.java

기존 채팅방에서 새로운 메시지 발생 시 메시지를 publish 처리를 했습니다.
- MessagMapping Handler 작성
- STOMP 테스트코드 작성
- close #222

feat: 기존 채팅방에서 새로운 메시지 발생 시 메시지를 publish 한다.

---

.gitignore
build.gradle
src/main/java/com/clova/anifriends/global/aspect/LogAspect.java
src/main/resources/logback-spring.xml

- 스프링 aop를 이용한 예외 상황, 클라이언트 요청 로깅을 추가하였습니다.
- 로그 레벨 별 파일 출력 설정을 추가하였습니다.
- debug, info, warn, error 레벨에 대한 로그를 파일로 출력합니다.
- 콘솔에는 info 레벨 이상의 로그만 출력됩니다.
- aop 로깅을 위한 `LogAspect` 추가
- 로그 설정 파일 `logback-spring.xml` 추가
- close #250

feat: 로그 aop 와 logback 설정 파일을 추가한다.

---

src/main/java/com/clova/anifriends/domain/auth/controller/AuthController.java
src/main/java/com/clova/anifriends/domain/auth/dto/request/LoginRequest.java
src/main/java/com/clova/anifriends/domain/auth/service/AuthService.java
src/main/java/com/clova/anifriends/domain/shelter/Shelter.java
src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterDeviceToken.java
src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java
src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerDeviceToken.java
src/test/java/com/clova/anifriends/domain/auth/controller/AuthControllerTest.java
src/test/java/com/clova/anifriends/domain/auth/service/AuthServiceTest.java
src/test/java/com/clova/anifriends/domain/shelter/ShelterTest.java
src/test/java/com/clova/anifriends/domain/shelter/wrapper/ShelterDeviceTokenTest.java
src/test/java/com/clova/anifriends/domain/volunteer/VolunteerTest.java
src/test/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerDeviceTokenTest.java

로그인시 requestBody에 deviceToken을 추가로 받는다.
- LoginRequestDTO에 deviceToken optional로 추가
- loginService에서 deviceToken이 Null이 아닐 경우 update
- 관련 테스트 코드 작성
- close #192

feat: 로그인 시 클라이언트로부터 fcm token을 받는다.

---

src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java

jpql 의 where 문에서 Enum 을 사용하도록 수정한다.
jpql 의 where 문에서 Enum 을 사용하도록 수정한다.
- close #265

refactor: jpql 의 where 문에서 Enum 을 사용하도록 수정한다.

---

src/main/java/com/clova/anifriends/domain/animal/controller/AnimalController.java
src/main/java/com/clova/anifriends/domain/animal/dto/request/FindAnimalsByShelterRequest.java
src/main/java/com/clova/anifriends/domain/animal/dto/request/FindAnimalsByVolunteerRequest.java
src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryCustom.java
src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryImpl.java
src/main/java/com/clova/anifriends/domain/animal/service/AnimalService.java
src/main/java/com/clova/anifriends/domain/animal/vo/AnimalNeuteredFilter.java
src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantService.java
src/main/java/com/clova/anifriends/domain/chat/service/ChatRoomService.java
src/test/java/com/clova/anifriends/domain/animal/controller/AnimalControllerTest.java
src/test/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryTest.java
src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceTest.java

보호 동물 목록 조회 시 중성화 필터링 Enum 을 사용한다.
AnimalNeuteredFilter Enum
```
public enum AnimalNeuteredFilter implements EnumType {
IS_NEUTERED(true),
IS_NOT_NEUTERED(false),
;
}
```
- close #280

refactor: 보호 동물 목록 조회 시 중성화 필터링 Enum 을 사용한다.

---

build.gradle

- 프로메테우스, 그라파나를 이용한 모니터링을 위해 액츄에이터, 프로메테우스 의존성을 추가하였습니다.
- build.gradle 액츄에이터, 프로메테우스 의존성 추가
- application-default.yml 메트릭 설정 추가
- close #274

chore: 프로덕션 환경의 모니터링 툴을 추가한다.

---

src/test/java/com/clova/anifriends/AnifriendsApplicationTests.java
src/test/java/com/clova/anifriends/base/BaseControllerTest.java

- 도커 컴포즈를 수정하였습니다.
- 도커 컴포즈 볼륨 마운트 추가
- close #305

chore: 컨테이너 내부에 생성되는 로그를 머신에 출력되도록 변경한다.

---

src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java
src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantService.java
src/main/java/com/clova/anifriends/domain/recruitment/vo/RecruitmentInfo.java
src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java
src/main/java/com/clova/anifriends/domain/volunteer/repository/VolunteerRepository.java
src/main/java/com/clova/anifriends/domain/volunteer/vo/VolunteerTemperature.java
src/test/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepositoryTest.java
src/test/java/com/clova/anifriends/domain/volunteer/vo/VolunteerTemperatureTest.java

- 봉사자의 출석에 따른 온도 증감 로직 추가
- `NO_SHOW` -> `ATTENDANCE` 일 경우 온도 +10
- `ATTENDANCE` -> `NO_SHOW` 일 경우 온도 -10
- close #323

feat: 봉사자의 출석 변경에 따른 온도 증감 로직을 추가한다.

---

src/docs/asciidoc/index.adoc
src/main/resources/static/docs/index.html

notification 관련 문서화를 추가한다.
- notification 관련 문서화를 추가
- close #333

docs: notification 관련 문서화를 추가한다.

---

src/docs/asciidoc/index.adoc
src/main/resources/static/docs/index.html
src/test/java/com/clova/anifriends/domain/volunteer/controller/VolunteerControllerTest.java

Volunteer 관련 문서화를 추가한다.
Volunteer 관련 문서화를 추가한다.
- close #336

docs: Volunteer 관련 문서화를 추가한다.

---

.github/workflows/cd-dev.yml
nginx/nginx.conf
src/main/java/com/clova/anifriends/global/event/CacheWarmer.java
src/main/resources/logback-spring.xml

- dev 서버에 https를 적용했습니다.
- nginx.conf에 443 ssl 관련 설정 추가
서브 모듈 설정 추가
- docker-compose에 certbot 추가
- 인증서 기간 자동 연장을 위한 shell 파일 추가
- dev 서버에 https를 적용
- close #329

chore: dev 서버에 https를 적용한다. 

---

src/docs/asciidoc/index.adoc

리뷰, 보호소에 대한 누락된 API 문서화를 추가한다. 
- 리뷰 도메인에서 누락된 API 문서화
- 보호소 도메인에서 누락된 API 문서화
- close #334

docs: 리뷰, 보호소에 대한 누락된 API 문서화를 추가한다. 

---

src/docs/asciidoc/index.adoc
src/main/java/com/clova/anifriends/global/config/SecurityConfig.java
src/test/resources/application.yml

- animal에 대한 API 문서화
- animal에 대한 API 문서화
- close #340

docs: 보호 동물에 대한 누락된 API 문서화를 추가한다.

---

src/docs/asciidoc/index.adoc
src/main/resources/static/docs/index.html
src/test/java/com/clova/anifriends/docs/enumtype/EnumDocsController.java
src/test/java/com/clova/anifriends/docs/enumtype/EnumDocumentationTest.java

- 채팅 도메인에 대하여 누락된 API 문서화를 추가하였습니다.
- 채팅 도메인 API 문서화 추가
- close #344

docs: 채팅 도메인에 대해 누락된 API 문서화를 추가한다. 

---

src/main/java/com/clova/anifriends/domain/review/dto/response/FindVolunteerReviewsResponse.java
src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java

- FindVolunteerReviewsResponse에 shelterId 추가
- FindVolunteerReviewsResponse에 shelterId 추가
- close #355

refactor: 봉사자가 작성한 후기 리스트(봉사자), 봉사자가 작성한 후기 리스트(보호소) response에 shelterId를 추가한다.

---

src/docs/asciidoc/index.adoc
src/main/java/com/clova/anifriends/domain/auth/controller/AuthController.java
src/main/java/com/clova/anifriends/domain/auth/service/AuthService.java
src/main/resources/static/docs/index.html
src/test/java/com/clova/anifriends/domain/auth/controller/AuthControllerTest.java
src/test/java/com/clova/anifriends/domain/auth/service/AuthServiceTest.java
src/test/java/com/clova/anifriends/domain/auth/support/AuthFixture.java

- 로그아웃 기능을 구현하였습니다.
- 발행한 리프레시 토큰 쿠키를 무효화하기 위하여 max-age 가 0으로 설정된 쿠키가 재발행됩니다.
- 로그아웃 api, 서비스 로직 구현
- close #345

feat: 로그아웃 기능을 구현한다.

---

src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentDetailResponse.java
src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentsByShelterResponse.java
src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentsResponse.java
src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepository.java
src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
src/main/resources/static/docs/index.html
src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentScheduledTest.java
src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
src/test/resources/application.yml

봉사 모집글 자동 마감 로직을 추가한다. 
- dto에서 isClosed -> isClosed || 마감 시간 < 현재 시간
- 매일 새벽 1시에 deadline이 지난 모집을 마감 처리한다.
- close #377

fix: 봉사 모집글 자동 마감 로직을 추가한다. 

---

README.md

- readme에 api 명세, 이슈/해결 글을 추가했습니다.
- EC2가 닫히는 경우를 대비해 API 명세 사진을 넣었는데 괜찮은지 궁금합니다.
- readme에 api 명세, 이슈/해결 글을 추가
- close #429

docs: readme에 api 명세, 이슈/해결 글을 추가한다.

---

README.md

- 로그 파일을 하루에 한 번 체크해서 EC2 디스크 용량이 적어지면 S3에 압축해서 저장하고 로그를 초기화하는 shell script 작성
- readme에 해결과정 추가
- 해결과정 : https://prgrms.notion.site/215c4c3543f7457eb16739de036bd3ad?pvs=4
- 로그 파일을 하루에 한 번 체크해서 EC2 디스크 용량이 적어지면 S3에 압축해서 저장하고 로그를 초기화하는 shell script
- close #437

feat: 로그 파일 용량이 커질 때 관리하는 shell script를 작성한다.
